name: Notify Discord on Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send commit info to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s" || echo "No commit message found")
          AUTHOR_NAME=$(git log -1 --pretty=format:"%an" || echo "Unknown author")
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          MESSAGE="🛠️ New commit by $AUTHOR_NAME: $COMMIT_MESSAGE\n🔗 $COMMIT_URL"
          echo "Sending message: $MESSAGE"
          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg msg "$MESSAGE" '{content: $msg}')"
